// Copyright 2026 Jon Miller. SPDX-License-Identifier: Apache-2.0
import express from "express";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { z } from "zod";
import { Store } from "./store.js";

export function createMcp(store,tenant){const s=new McpServer({name:"Continuity Kernel / CK-01 MCP Adapter",version:"0.4.0"});s.registerTool("ck01_propose_candidate",{description:"Record an external candidate assertion; never authorizes CK-01 state.",inputSchema:{claim:z.string().min(1).max(10000)}},({claim})=>({content:[{type:"text",text:JSON.stringify(store.propose(tenant,claim))}]}));s.registerTool("ck01_record_provenance",{inputSchema:{candidate_id:z.string().uuid(),source_id:z.string().min(1).max(255),statement:z.string().min(1).max(10000)}},(x)=>({content:[{type:"text",text:JSON.stringify(store.provenance(tenant,x.candidate_id,x.source_id,x.statement))}]}));s.registerTool("ck01_supersede_candidate",{inputSchema:{candidate_id:z.string().uuid(),replacement_candidate_id:z.string().uuid()}},(x)=>({content:[{type:"text",text:JSON.stringify(store.supersede(tenant,x.candidate_id,x.replacement_candidate_id))}]}));s.registerTool("ck01_continuity_brief",{inputSchema:{}},()=>({content:[{type:"text",text:JSON.stringify({tenant,candidates:store.brief(tenant),reference_only:true})}]}));return s;}

export function createApp({databasePath=process.env.CK01_DATABASE_PATH||"./data/ck01-adapter.sqlite",apiKeys=Object.fromEntries((process.env.CK01_API_KEYS||"").split(",").filter(Boolean).map(x=>{const i=x.indexOf(":");return i<1?["",""]:[x.slice(i+1),x.slice(0,i)];}))}={}){const app=express(),store=new Store(databasePath);app.use(express.json({limit:"256kb"}));app.get("/health",(_q,r)=>r.json({ok:true,name:"Continuity Kernel / CK-01",version:"0.4.0"}));app.post("/mcp",async(req,res)=>{const key=req.header("authorization")?.replace(/^Bearer /i,"");const tenant=key&&apiKeys[key];if(!tenant)return res.status(401).json({error:"authenticated tenant context required"});const server=createMcp(store,tenant);const transport=new StreamableHTTPServerTransport({sessionIdGenerator:undefined});res.on("close",()=>{transport.close();server.close();});await server.connect(transport);await transport.handleRequest(req,res,req.body);});app.all("/mcp",(_q,r)=>r.status(405).json({error:"stateless POST only"}));return {app,store};}
if(process.argv[1]===new URL(import.meta.url).pathname.replace(/^\/(.:)/,"$1")){const {app}=createApp();app.listen(Number(process.env.PORT||3000),()=>console.error("CK-01 adapter listening"));}


